## Load MNIST on Python 3.x

In [1]:
import pickle
import gzip
import keras
from keras.layers import Dense
from keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten
from keras.models import Sequential
from PIL import Image
import os
import numpy as np
import scipy
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from pylab import *
from sklearn.metrics import confusion_matrix
import itertools

Using TensorFlow backend.


In [2]:
filename = 'D:\sem1\intro to ml\project3\mnist.pkl.gz'
f = gzip.open(filename, 'rb')
training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
#print(len(training_data))
#print(training_data[1])
x_train= training_data[0]
y_train = training_data[1]
x=training_data[0]
y=training_data[1]
x_test = test_data[0]
y_test = test_data[1]
val_x = validation_data[0]
val_y = validation_data[1]
x_train,y_train = training_data
x_test,y_test = test_data
print(len(y_test ))
#print(tx)
#print(ty)
f.close()

10000


## Load USPS on Python 3.x

In [3]:
USPSMat  = []
USPSTar  = []
curPath  = r'D:\sem1\intro to ml\project3\USPSdata\USPSdata\Numerals'
savedImg = []

for j in range(0,10):
    curFolderPath = curPath + '/' + str(j)
    imgs =  os.listdir(curFolderPath)
    for img in imgs:
        curImg = curFolderPath + '/' + img
        if curImg[-3:] == 'png':
            img = Image.open(curImg,'r')
            img = img.resize((28, 28))
            savedImg = img
            imgdata = (255-np.array(img.getdata()))/255
            USPSMat.append(imgdata)
            USPSTar.append(j)
us_testx = USPSMat[0:2000]
us_testy = USPSMat[0:2000]
testx= USPSMat
testy = USPSTar
testxnn= np.asarray(USPSMat)
num_classes = 10
USPSTarnn = keras.utils.to_categorical(USPSTar, num_classes)
testynn = USPSTarnn
print(len(testx ) )
#print(len(testy))

19999


In [69]:
def perform_log_reg(train_features, target, steps):
    weight_matrix = []
    a_mat = np.zeros((10))
    y = np.zeros((10))

    for i in range(10):
        dim1 = np.zeros(train_features.shape[1])
        weight_matrix.append(dim1)
        
    for step in range(steps):
        x_row = train_features[step]
        tar_row = target[step]
        total = 0
        for i in range(10):
            bias_value = 0
            a_mat[i] = np.dot(weight_matrix[i].T, x_row) + bias_value
            total = total + np.exp(a_mat[i])
        for i in range(10):
            y[i] = (np.exp(a_mat[i])) / (total)
        for i in range(10):
            computed_diff = (y[i] - tar_row[i]) * x_row
            weight_matrix[i] = weight_matrix[i] - (0.01 * computed_diff)

    return weight_matrix
def oneHotIt(Y):
    m = Y.shape[0]
    targets = np.array(Y)
    OHX = scipy.sparse.csr_matrix((np.ones(m), (Y, np.array(range(m)))))
    OHX = np.array(OHX.todense()).T
    #OH = np.zeros((m,10))
    #OH[(np.arange(m),target)] =1
    return OHX

def prediction(train_features, target, steps, wx):
    weight_matrix = wx
    a_mat = np.zeros((10))
    yy = np.zeros(steps)
    for i in range(10):
        dim1 = np.zeros(train_features.shape[1])
        weight_matrix.append(dim1)
        
    for step in range(steps):
        x_row = train_features[step]
        tar_row = target[step]
        total = 0
        for i in range(10):
            bias_value = 0
            a_mat[i] = np.dot(weight_matrix[i].T, x_row) + bias_value
            total = total + np.exp(a_mat[i])
        y = np.zeros((10))

        for i in range(10):
            y[i] = (np.exp(a_mat[i])) / (total)
        #print("Ypreds")
        #print(np.argmax(y))
        #print(tar_row)
        
        yy[step] = (np.argmax(y)).astype(int)
    return yy

def predictionUSPS(train_features, target, steps, wx):
    weight_matrix = wx
    a_mat = np.zeros((10))
    yy = np.zeros(steps)
    for i in range(10):
        dim1 = np.zeros(len(train_features))
        weight_matrix.append(dim1)
        
    for step in range(steps):
        x_row = train_features[step]
        tar_row = target[step]
        total = 0
        for i in range(10):
            bias_value = 0
            a_mat[i] = np.dot(weight_matrix[i].T, x_row) + bias_value
            total = total + np.exp(a_mat[i])
        y = np.zeros((10))

        for i in range(10):
            y[i] = (np.exp(a_mat[i])) / (total)
        #print("Ypreds")
        #print(np.argmax(y))
        #print(tar_row)
        
        yy[step] = (np.argmax(y)).astype(int)
    return yy

In [70]:
#w = np.zeros([x.shape[1],len(np.unique(y))])
train_features = x_train
target = oneHotIt(y_train)
steps = 10000
steps_train = 50000
def getacc(ma,tar):
    acc = 0
    for i in range(0,len(ma)):
        if(int(ma[i]) == tar[i]):
            acc = acc + 1
    return (acc / 10000)       

wx = perform_log_reg(train_features, target, steps_train)
ma = prediction(x_test,y_test,steps, wx)
#ma_usps = prediction(testx,testy,steps,wx)
xx_mnist = []
tar = y_test
#tar_usps = testy
#print(tar)
for ele in ma:
    xx_mnist.append(int(ele))
#print(xx)    
print("MNIST Accuracy :" , getacc(xx_mnist,tar))
#print("USPS Accuracy :", getacc(ms_usps,tar_usps))
 


MNIST Accuracy : 0.907


NameError: name 'out' is not defined

In [71]:
out_mnist = confusion_matrix(y_test, ma)
print("confusion matrix :" , out_mnist)

confusion matrix  [[ 958    0    1    5    0    2    8    2    4    0]
 [   0 1113    0    5    0    2    3    2   10    0]
 [  12   11  881   35    6    4   13   21   42    7]
 [   1    0   11  919    0   45    0   13   14    7]
 [   2    3    3    2  881    0   13    6   12   60]
 [  10    5    1   40    4  780    8    8   31    5]
 [  14    3    3    2    7   36  884    3    6    0]
 [   2   11   19    9    5    0    0  956    5   21]
 [   7   10    3   44    7   66    7   17  801   12]
 [   8    8    0   11   17   19    1   45    3  897]]


In [ ]:
#w = np.zeros([x.shape[1],len(np.unique(y))])
train_features = x_train
target = oneHotIt(y_train)
steps = 19999
def getacc(ma,tar):
    acc = 0
    for i in range(0,len(ma)):
        if(int(ma[i]) == tar[i]):
            acc = acc + 1
    return (acc / 19999)
wx = perform_log_reg(train_features, target, steps)
#ma = prediction(x_test,y_test,steps, wx)
ma_usps = predictionUSPS(USPSMat,testy,steps,wx)
xx_usps = []
tar_usps = testy
#print(tar)
for ele in ma_usps:
    xx_usps.append(ele)
print("USPS Accuracy :", getacc(ma_usps,tar_usps))


In [73]:
out_usps = confusion_matrix(testy, ma_usps)
print("confusion matrix " , out_usps)

confusion matrix  [[ 477    5  239   69  217  287   90   76  225  315]
 [ 137  337  106  310  213  103   38  442  303   11]
 [ 134   28 1118  155   46  160   84   95  154   25]
 [  76    4  107 1155   14  412   11   71  110   40]
 [  47   73   30   47  936  143   53  161  348  162]
 [ 133   21  149  144   29 1260  103   63   79   19]
 [ 190   15  376  109   72  428  684   17   73   36]
 [ 163  218  170  423   73  126   20  386  371   50]
 [ 191   35   98  172   93  758   88   38  460   67]
 [  33  171  105  431  136  106   14  430  406  168]]


# Neural network

In [4]:
num_classes=10
image_vector_size=28*28
x_trainn = x_train.reshape(x_train.shape[0], image_vector_size)
x_testn = x_test.reshape(x_test.shape[0], image_vector_size)
val_x = val_x.reshape(val_x.shape[0], image_vector_size)
val_y = keras.utils.to_categorical(val_y, num_classes)
y_trainn = keras.utils.to_categorical(y_train, num_classes)
y_testn = keras.utils.to_categorical(y_test, num_classes)
image_size = 784
USPSTa = USPSTar
USPSTar = keras.utils.to_categorical(USPSTar, num_classes)
model = Sequential()
model.add(Dense(units=32, activation='sigmoid', input_shape=(image_size,)))
model.add(Dense(units=50, activation='relu',input_shape=(image_size,)))
#model.add(Dropout(0.5))
#model.add(Dense(units=10, activation='softmax',input_shape=(image_size,)))
model.add(Dense(units=num_classes, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])
history = model.fit(x_trainn, y_trainn, batch_size=6000, epochs=600,verbose=False,validation_split=.1)
loss1,accuracy1 = model.evaluate(testxnn,testynn,verbose=False)
#print("MNIST: "  ,loss)
print("USPS: " ,accuracy1)  



USPS:  0.3168658432891842


In [5]:
tar_nn_us = np.asarray(USPSTar)
pnn_usps = model.predict_classes(testxnn)
pnn_us = model.predict(testxnn)
nn_out_usps = confusion_matrix(tar_nn_us, pnn_usps)
print("Neural Network confusion matrix USPS: " , nn_out_usps)

ValueError: Classification metrics can't handle a mix of multilabel-indicator and multiclass targets

In [6]:

loss,accuracy = model.evaluate(x_testn, y_testn, verbose=False)
#loss,accuracy_val = model.evaluate(val_x, val_y, verbose=False)
pnn_mnist = model.predict_classes(x_testn)
#pnn_mnist = pnn_mnist_x
print("MNIST: " ,accuracy)
#print("MNIST Val: " ,accuracy_val)
nn_out_usps = confusion_matrix(y_test, pnn_mnist)
print("Neural network confusion matrix MNIST: " , nn_out_usps)

MNIST:  0.9615
Neural network confusion matrix MNIST:  [[ 961    0    3    2    1    2    5    2    2    2]
 [   0 1118    6    1    0    1    2    2    5    0]
 [   3    1  988    8    4    0    6    9   12    1]
 [   2    3    8  963    1    9    0   12    9    3]
 [   1    1    2    1  947    0    9    5    2   14]
 [   4    1    1   10    5  849    8    3    5    6]
 [   7    2    3    1    5    4  931    0    5    0]
 [   1    3   11    7    2    1    0  993    1    9]
 [   5    1    8   15    4   10    6    6  915    4]
 [   4    2    0   12   20    6    1    6    8  950]]


In [47]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
from keras import backend as K
K.set_image_dim_ordering('th')
X_train, Y_train = training_data
X_test, Y_test = test_data
# reshape to be [samples][pixels][width][height]
X_train = X_train.reshape(X_train.shape[0], 1, 28, 28).astype('float32')
X_test = X_test.reshape(X_test.shape[0], 1, 28, 28).astype('float32')

#testy = USPSTar
###########################
testxcnn= np.asarray(USPSMat)
num_classes = 10
#USPSTarcnn = keras.utils.to_categorical(USPSTar, num_classes)
USPSTarcnn = USPSTar
testycnn = USPSTarcnn

testxcnn = testxcnn.reshape(testxcnn.shape[0], 1, 28, 28).astype('float32')
#testycnn = X_test.reshape(testycnn.shape[0], 1, 28, 28).astype('float32')

testxcnn = testxcnn / 255
# one hot encode outputs
testycnn = np_utils.to_categorical(testycnn)
####################

# normalize inputs from 0-255 to 0-1
X_train = X_train / 255
X_test = X_test / 255
# one hot encode outputs
Y_train = np_utils.to_categorical(Y_train)
Y_test = np_utils.to_categorical(Y_test)
num_classes = Y_test.shape[1]

def cnn_model():
    # create model
    model = Sequential()
    model.add(Conv2D(32, (5, 5), input_shape=(1, 28, 28), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(15, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))# Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [48]:
# build the model
model = cnn_model()
# Fit the model
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=20, batch_size=200, verbose=2)
# Final evaluation of the model
scores_mnist = model.evaluate(X_test, Y_test, verbose=0)
pcnn_mnist = model.predict(X_test)
score_usps = model.evaluate(testxcnn,testycnn, verbose=0)
pcnn_usps = model.predict(testxcnn)
#print("CNN Error: %.2f%%" % (100-scores[1]*100))

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
 - 2s - loss: 1.4219 - acc: 0.5376 - val_loss: 0.5475 - val_acc: 0.8370
Epoch 2/20
 - 2s - loss: 0.5781 - acc: 0.8183 - val_loss: 0.4054 - val_acc: 0.8843
Epoch 3/20
 - 2s - loss: 0.4588 - acc: 0.8596 - val_loss: 0.3173 - val_acc: 0.9078
Epoch 4/20
 - 2s - loss: 0.3693 - acc: 0.8879 - val_loss: 0.2515 - val_acc: 0.9280
Epoch 5/20
 - 2s - loss: 0.3039 - acc: 0.9077 - val_loss: 0.2056 - val_acc: 0.9376
Epoch 6/20
 - 2s - loss: 0.2575 - acc: 0.9205 - val_loss: 0.1683 - val_acc: 0.9529
Epoch 7/20
 - 2s - loss: 0.2235 - acc: 0.9320 - val_loss: 0.1461 - val_acc: 0.9569
Epoch 8/20
 - 2s - loss: 0.2000 - acc: 0.9381 - val_loss: 0.1262 - val_acc: 0.9623
Epoch 9/20
 - 2s - loss: 0.1785 - acc: 0.9441 - val_loss: 0.1123 - val_acc: 0.9671
Epoch 10/20
 - 2s - loss: 0.1592 - acc: 0.9500 - val_loss: 0.0979 - val_acc: 0.9700
Epoch 11/20
 - 2s - loss: 0.1462 - acc: 0.9546 - val_loss: 0.0926 - val_acc: 0.9717
Epoch 12/20
 - 2s - loss: 0.1333 - 

ValueError: Error when checking target: expected dense_15 to have 2 dimensions, but got array with shape (19999, 10, 2)

In [ ]:
print(scores_mnist[len(scores_mnist)-3])
print(score_usps[len(score_usps)-3])


# SVM and Random Forest

In [88]:
# SVM & RandomForest
n_train = 50000
n_test = 10000
indices = arange(len(x_train))
train_idx = arange(0,n_train)
test_idx = arange(n_train+1,n_train+n_test)
#X_train, y_train = mnist.data[train_idx], mnist.target[train_idx]
#X_test, y_test = mnist.data[test_idx], mnist.target[test_idx]
classifier2 = RandomForestClassifier(n_estimators=10)
classifier2.fit(x_train, y_train)
rf_preds_mnist = classifier2.predict(x_test)
rf_preds_usps = classifier2.predict(testx)
#print((preds == y_train).mean())

acc_rf = accuracy_score(testy, rf_preds_usps)
print(acc_rf)
# SVM
rf_out_usps = confusion_matrix(testy, rf_preds_usps)
print("RF confusion matrix USPS: " , rf_out_usps)


0.3064653232661633
RF confusion matrix USPS:  [[643  41 307  69 346 176 132 112  12 162]
 [ 89 497 202 128  48  78  50 871  29   8]
 [220  98 910 150  87 200  70 230  21  13]
 [125  53 191 994  88 350  21 126  30  22]
 [ 42 194 183 101 846 153  56 321  39  65]
 [210  92 236 277  74 891  70 109  14  27]
 [351  85 374 103 155 284 511  95  12  30]
 [111 385 323 270  48 186  37 603  22  15]
 [145 123 281 268 160 653  96 100 122  52]
 [ 71 327 300 317 218 133  30 407  85 112]]


In [90]:
acc_rf_mnist =  accuracy_score(y_test, rf_preds_mnist)
rf_out_mnist = confusion_matrix(y_test, rf_preds_mnist)
print("RF confusion matrix MNIST: " , rf_out_mnist)
print(acc_rf_mnist)
print(len(rf_preds_mnist) )

RF confusion matrix MNIST:  [[ 965    0    0    1    0    2    7    2    3    0]
 [   0 1117    3    4    1    2    5    0    3    0]
 [  11    3  984    7    4    2    3   10    7    1]
 [   5    3   17  930    0   25    1   11   14    4]
 [   3    0    7    3  934    2    9    1    3   20]
 [  10    3    4   30   10  814    8    2    6    5]
 [  12    3    4    2    6    9  918    1    3    0]
 [   1    8   19    8   10    0    0  959    3   20]
 [   6    2   14   14    7   13    7    8  894    9]
 [   8    5    2   16   30    6    2    8   15  917]]
0.9432
10000


In [53]:
classifier1 = SVC(kernel='rbf')
classifier1.fit(x_train, y_train)
#print((testx.shape()))
sv_preds1_mnist = classifier1.predict(x_test)
sv_preds1_usps = classifier1.predict(testx)
print((sv_preds1_mnist == y_test).mean())
print((sv_preds1_usps == testy).mean())

print("SVM done")

C:\Users\Jayanth\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9435
0.38541927096354817
SVM done


In [92]:
sv_out_mnist = confusion_matrix(y_test, sv_preds1_mnist)
print("RF confusion matrix MNIST: " , sv_out_mnist)

RF confusion matrix MNIST:  [[ 967    0    1    0    0    5    4    1    2    0]
 [   0 1120    2    3    0    1    3    1    5    0]
 [   9    1  962    7   10    1   13   11   16    2]
 [   1    1   14  950    1   17    1   10   11    4]
 [   1    1    7    0  937    0    7    2    2   25]
 [   7    4    5   33    7  808   11    2   10    5]
 [  10    3    4    1    5   10  924    0    1    0]
 [   2   13   22    5    7    1    0  954    4   20]
 [   4    6    6   14    8   24   10    8  891    3]
 [  10    6    0   12   33    5    1   14    6  922]]


In [91]:
sv_out_usps = confusion_matrix(testy, sv_preds1_usps)
print("RF confusion matrix USPS: " , sv_out_usps)

RF confusion matrix USPS:  [[ 573    2  428   19  285  248   73   44    6  322]
 [ 110  429  285  137  273  180   46  501   22   17]
 [ 128   18 1402   59   39  198   61   57   23   14]
 [  76    3  186 1123   11  483    5   70   27   16]
 [  18   67   91   14 1167  267   22  194   69   91]
 [ 108   17  257  102   25 1367   60   43   15    6]
 [ 197    7  489   24   98  394  748   13    7   23]
 [  50  225  457  265   57  416   15  452   41   22]
 [  73   25  209  193   87 1006   95   41  244   27]
 [  26  166  228  278  213  165    8  499  214  203]]


In [52]:
#### Ensemble
from scipy import stats
final_pred = np.array([])
for i in range(0,len(x_test)):
    final_pred = np.append(final_pred, stats.mode([xx_mnist[i],rf_preds_mnist[i],pnn_mnist[i],sv_preds1_mnist[i]]) )
print(final_pred)
fin

[7. 4. 2. ... 4. 6. 4.]


In [64]:
finalacc = 0

for i in range(0,len(x_test)):
    if(int( int(final_pred[i]) ) == int(y_test[i]) ):
        finalacc = finalacc + 1
print("final acc mnist : " ,finalacc / 10000 )

final acc mnist :  0.0978


In [59]:
len(y_test)

10000

In [60]:
len(x_test)


10000